# -*- coding: utf-8 -*-
"""app .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ree2bkHJUWa9mKL0VhEydWttlMas1CJQ
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(
    page_title="Employee Engagement & Burnout Dashboard",
    page_icon="📊",
    layout="wide"
)
st.title("📊 Employee Engagement & Burnout Intelligence")
st.subheader("Preventive Employee Experience Analytics")

st.write(
    "Interactive HR analytics dashboard for monitoring employee "
    "engagement, burnout risk, workload stress and career-stage patterns."
)

df = pd.read_csv("Palo Alto Networks.csv")

df.head()

df.shape

df.columns.tolist()

df.isnull().sum()

df.duplicated().sum()

df.duplicated().sum()

df.dtypes

df.describe()

for col in [
    "JobInvolvement",
    "JobSatisfaction",
    "EnvironmentSatisfaction",
    "RelationshipSatisfaction",
    "WorkLifeBalance"
]:
    print(col)
    print(df[col].value_counts().sort_index())
    print()

df = df.drop_duplicates()

satisfaction_cols = [
    "JobInvolvement",
    "JobSatisfaction",
    "EnvironmentSatisfaction",
    "RelationshipSatisfaction",
    "WorkLifeBalance"
]

for col in satisfaction_cols:
    df[col] = df[col].fillna(df[col].median())

df[satisfaction_cols].isnull().sum()

df["Engagement_Index"] = df[
    [
        "JobInvolvement",
        "JobSatisfaction",
        "EnvironmentSatisfaction",
        "RelationshipSatisfaction"
    ]
].mean(axis=1)

df["Engagement_Score"] = (
    (df["Engagement_Index"] - 1) / 3 * 100
)

df[[
    "Engagement_Index",
    "Engagement_Score"
]].head()

def engagement_category(score):
    if score < 50:
        return "Low"
    elif score < 75:
        return "Medium"
    else:
        return "High"

df["Engagement_Level"] = df["Engagement_Score"].apply(
    engagement_category
)

df["Engagement_Level"].value_counts()

df["Burnout_Risk_Score"] = 0

df.loc[df["OverTime"] == "Yes", "Burnout_Risk_Score"] += 1

df.loc[df["WorkLifeBalance"] <= 2, "Burnout_Risk_Score"] += 1

def burnout_level(score):
    if score == 2:
        return "High"
    elif score == 1:
        return "Medium"
    else:
        return "Low"

df["Burnout_Risk"] = df["Burnout_Risk_Score"].apply(
    burnout_level
)

df["Burnout_Risk"].value_counts()

df["WorkLifeBalance_Index"] = df["WorkLifeBalance"]

df["WorkLifeBalance"].mean()

satisfaction_cols = [
    "JobSatisfaction",
    "EnvironmentSatisfaction",
    "RelationshipSatisfaction",
    "JobInvolvement"
]

df["Satisfaction_Stability"] = df[satisfaction_cols].std(axis=1)

df["Satisfaction_Stability_Score"] = (
    100 - (df["Satisfaction_Stability"] / 1.5 * 100)
).clip(0, 100)

df["Overtime_Flag"] = np.where(
    df["OverTime"] == "Yes", 1, 0
)

travel_map = {
    "Non-Travel": 0,
    "Travel_Rarely": 1,
    "Travel_Frequently": 2
}
df["Travel_Intensity"] = df["BusinessTravel"].map(travel_map)
df["Workload_Stress_Score"] = (
    df["Overtime_Flag"] +
    df["Travel_Intensity"]
)

fig = px.histogram(
    df,
    x="Engagement_Score",
    nbins=20,
    title="Employee Engagement Score Distribution"
)

fig.show()

fig = px.box(
    df,
    x="OverTime",
    y="Engagement_Score",
    title="Engagement: Overtime vs Non-Overtime"
)

fig.show()

fig = px.box(
    df,
    x="WorkLifeBalance",
    y="Engagement_Score",
    title="Engagement by Work-Life Balance"
)

fig.show()

dept = (
    df.groupby("Department")["Engagement_Score"]
    .mean()
    .reset_index()
)

fig = px.bar(
    dept,
    x="Department",
    y="Engagement_Score",
    title="Average Engagement by Department"
)

fig.show()

joblevel = (
    df.groupby("JobLevel")["Engagement_Score"]
    .mean()
    .reset_index()
)

fig = px.bar(
    joblevel,
    x="JobLevel",
    y="Engagement_Score",
    title="Engagement by Job Level"
)

fig.show()

fig = px.scatter(
    df,
    x="YearsAtCompany",
    y="Engagement_Score",
    trendline="ols",
    title="Tenure vs Engagement"
)

fig.show()

df.groupby(
    "YearsSinceLastPromotion"
)["Engagement_Score"].mean()

df.groupby(
    "YearsInCurrentRole"
)["Engagement_Score"].mean()

attrition_engagement = (
    df.groupby("Attrition")["Engagement_Score"]
    .mean()
    .reset_index()
)

attrition_engagement["Attrition"] = (
    attrition_engagement["Attrition"]
    .map({0: "Stayed", 1: "Left"})
)

fig = px.bar(
    attrition_engagement,
    x="Attrition",
    y="Engagement_Score",
    title="Engagement vs Employee Attrition"
)

fig.show()

import streamlit as st

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Engagement Index",
    f"{df['Engagement_Score'].mean():.1f}"
)

col2.metric(
    "High Burnout Risk",
    f"{(df['Burnout_Risk'].eq('High').mean()*100):.1f}%"
)

col3.metric(
    "Work-Life Balance",
    f"{df['WorkLifeBalance'].mean():.2f}"
)

col4.metric(
    "Low Engagement",
    f"{(df['Engagement_Level'].eq('Low').sum()):,}"
)

department = st.sidebar.multiselect(
    "Department",
    options=sorted(df["Department"].unique()),
    default=sorted(df["Department"].unique())
)

filtered_df = df[
    df["Department"].isin(department)
]

burnout = (
    filtered_df["Burnout_Risk"]
    .value_counts()
    .reset_index()
)

burnout.columns = ["Risk", "Employees"]

fig = px.bar(
    burnout,
    x="Risk",
    y="Employees",
    title="Burnout Risk Distribution"
)

st.plotly_chart(fig, use_container_width=True)

filtered_df[
    filtered_df["Burnout_Risk"] == "High"
]

priority = filtered_df[
    (filtered_df["Burnout_Risk"] == "High") &
    (filtered_df["Engagement_Level"] == "Low")
]

st.subheader("Priority Intervention Areas")

st.dataframe(
    priority[
        [
            "Department",
            "JobRole",
            "Engagement_Score",
            "Burnout_Risk",
            "OverTime",
            "WorkLifeBalance",
            "YearsSinceLastPromotion"
        ]
    ]
)

df.to_csv(
    "employee_engagement_analysis.csv",
    index=False
)

from google.colab import files

files.download("employee_engagement_analysis.csv")
